name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    runs-on: windows-latest
    steps:
      - uses: release-drafter/release-drafter@v5.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
